services:
  mqtt-broker:
    image: eclipse-mosquitto:2.1.2-alpine
    container_name: mqtt-broker
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./certs:/mosquitto/certs
    networks:
      - farm_network

  ## TERRENO A

  ambient_sensor_a: 
    build:
      context: ./ambient_sensor
      dockerfile: Dockerfile
    container_name: ambient_sensor_a
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USER=farm_admin
      - MQTT_BROKER_PASS=secure_farm
      - FIELD_NAME=field_a
    volumes:
      - ./certs:/app/certs:ro
    depends_on:
      - mqtt-broker
    networks:
      - farm_network

  terrain_sensor_a:
    build:
      context: ./terrain_sensor
      dockerfile: Dockerfile
    container_name: terrain_sensor_a
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USER=farm_admin
      - MQTT_BROKER_PASS=secure_farm
      - FIELD_NAME=field_a
      - FIELD_INIT_TYPE=Franco
      - FIELD_INIT_OXY=70.0
      - FIELD_INIT_MOIST=28.0
    volumes:
      - ./certs:/app/certs:ro
    depends_on:
      - mqtt-broker
    networks:
      - farm_network

  harvester_actuator_a:
    build:
      context: ./harvester
      dockerfile: Dockerfile
    container_name: harvester_a
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USER=farm_admin
      - MQTT_BROKER_PASS=secure_farm
      - FIELD_NAME=field_a
    volumes:
      - ./certs:/app/certs:ro
      - ./harvester/data:/app/data
    depends_on:
      - mqtt-broker
    networks:
      - farm_network

  seeder_actuator_a:
    build:
      context: ./seeder
      dockerfile: Dockerfile
    container_name: seeder_a
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USER=farm_admin
      - MQTT_BROKER_PASS=secure_farm
      - FIELD_NAME=field_a
    volumes:
      - ./certs:/app/certs:ro
    depends_on:
      - mqtt-broker
    networks:
      - farm_network

  irrigator_actuator_a:
    build:
      context: ./irrigator
      dockerfile: Dockerfile
    container_name: irrigator_a
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USER=farm_admin
      - MQTT_BROKER_PASS=secure_farm
      - FIELD_NAME=field_a
    volumes:
      - ./certs:/app/certs:ro
    depends_on:
      - mqtt-broker
    networks:
      - farm_network

  plantation_sensor_a:
    build:
      context: ./plantation_sensor
      dockerfile: Dockerfile
    container_name: plantation_sensor_a
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USER=farm_admin
      - MQTT_BROKER_PASS=secure_farm
      - FIELD_NAME=field_a
    volumes:
      - ./certs:/app/certs:ro
    depends_on:
      - mqtt-broker
    networks:
      - farm_network

  ## TERRENO B

  ambient_sensor_b: 
    build:
      context: ./ambient_sensor
      dockerfile: Dockerfile
    container_name: ambient_sensor_b
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USER=farm_admin
      - MQTT_BROKER_PASS=secure_farm
      - FIELD_NAME=field_b
    volumes:
      - ./certs:/app/certs:ro
    depends_on:
      - mqtt-broker
    networks:
      - farm_network

  terrain_sensor_b:
    build:
      context: ./terrain_sensor
      dockerfile: Dockerfile
    container_name: terrain_sensor_b
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USER=farm_admin
      - MQTT_BROKER_PASS=secure_farm
      - FIELD_NAME=field_b
      - FIELD_INIT_TYPE=Franco
      - FIELD_INIT_OXY=70.0
      - FIELD_INIT_MOIST=28.0
    volumes:
      - ./certs:/app/certs:ro
    depends_on:
      - mqtt-broker
    networks:
      - farm_network

  harvester_actuator_b:
    build:
      context: ./harvester
      dockerfile: Dockerfile
    container_name: harvester_b
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USER=farm_admin
      - MQTT_BROKER_PASS=secure_farm
      - FIELD_NAME=field_b
    volumes:
      - ./certs:/app/certs:ro
      - ./harvester/data:/app/data
    depends_on:
      - mqtt-broker
    networks:
      - farm_network

  seeder_actuator_b:
    build:
      context: ./seeder
      dockerfile: Dockerfile
    container_name: seeder_b
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USER=farm_admin
      - MQTT_BROKER_PASS=secure_farm
      - FIELD_NAME=field_b
    volumes:
      - ./certs:/app/certs:ro
    depends_on:
      - mqtt-broker
    networks:
      - farm_network

  irrigator_actuator_b:
    build:
      context: ./irrigator
      dockerfile: Dockerfile
    container_name: irrigator_b
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USER=farm_admin
      - MQTT_BROKER_PASS=secure_farm
      - FIELD_NAME=field_b
    volumes:
      - ./certs:/app/certs:ro
    depends_on:
      - mqtt-broker
    networks:
      - farm_network

  plantation_sensor_b:
    build:
      context: ./plantation_sensor
      dockerfile: Dockerfile
    container_name: plantation_sensor_b
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USER=farm_admin
      - MQTT_BROKER_PASS=secure_farm
      - FIELD_NAME=field_b
    volumes:
      - ./certs:/app/certs:ro
    depends_on:
      - mqtt-broker
    networks:
      - farm_network

  ## TERRENO C

  ambient_sensor_c: 
    build:
      context: ./ambient_sensor
      dockerfile: Dockerfile
    container_name: ambient_sensor_c
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USER=farm_admin
      - MQTT_BROKER_PASS=secure_farm
      - FIELD_NAME=field_c
    volumes:
      - ./certs:/app/certs:ro
    depends_on:
      - mqtt-broker
    networks:
      - farm_network

  terrain_sensor_c:
    build:
      context: ./terrain_sensor
      dockerfile: Dockerfile
    container_name: terrain_sensor_c
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USER=farm_admin
      - MQTT_BROKER_PASS=secure_farm
      - FIELD_NAME=field_c
      - FIELD_INIT_TYPE=Franco
      - FIELD_INIT_OXY=70.0
      - FIELD_INIT_MOIST=28.0
    volumes:
      - ./certs:/app/certs:ro
    depends_on:
      - mqtt-broker
    networks:
      - farm_network

  harvester_actuator_c:
    build:
      context: ./harvester
      dockerfile: Dockerfile
    container_name: harvester_c
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USER=farm_admin
      - MQTT_BROKER_PASS=secure_farm
      - FIELD_NAME=field_c
    volumes:
      - ./certs:/app/certs:ro
      - ./harvester/data:/app/data
    depends_on:
      - mqtt-broker
    networks:
      - farm_network

  seeder_actuator_c:
    build:
      context: ./seeder
      dockerfile: Dockerfile
    container_name: seeder_c
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USER=farm_admin
      - MQTT_BROKER_PASS=secure_farm
      - FIELD_NAME=field_c
    volumes:
      - ./certs:/app/certs:ro
    depends_on:
      - mqtt-broker
    networks:
      - farm_network

  irrigator_actuator_c:
    build:
      context: ./irrigator
      dockerfile: Dockerfile
    container_name: irrigator_c
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USER=farm_admin
      - MQTT_BROKER_PASS=secure_farm
      - FIELD_NAME=field_c
    volumes:
      - ./certs:/app/certs:ro
    depends_on:
      - mqtt-broker
    networks:
      - farm_network

  plantation_sensor_c:
    build:
      context: ./plantation_sensor
      dockerfile: Dockerfile
    container_name: plantation_sensor_c
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USER=farm_admin
      - MQTT_BROKER_PASS=secure_farm
      - FIELD_NAME=field_c
    volumes:
      - ./certs:/app/certs:ro
    depends_on:
      - mqtt-broker
    networks:
      - farm_network


  camp_manager:
    build:
      context: ./camp_manager
      dockerfile: Dockerfile
    container_name: camp_manager
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USER=farm_admin
      - MQTT_BROKER_PASS=secure_farm
      - CAMP_IDS=field_a,field_b,field_c
    volumes:
      - ./certs:/app/certs:ro
      - ./camp_manager/data:/app/data
    depends_on:
      - mqtt-broker
    networks:
      - farm_network

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: dashboard
    ports:
      - "8501:8501"
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USER=farm_admin
      - MQTT_BROKER_PASS=secure_farm
    volumes:
      - ./certs:/app/certs:ro
      - dashboard_data:/app/data
    depends_on:
      - mqtt-broker
    networks:
      - farm_network

volumes:
  dashboard_data:

networks:
  farm_network:
    driver: bridge