version: '3.8'

services:
  # Central message bus for all microservices
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883" # Host access for local debugging

  ambient-sensor:
    build: ./ambient_sensor
    container_name: ambient_sensor_app
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=1883
    depends_on:
      - mqtt-broker

  terrain-sensor:
    build: ./terrain_sensor
    container_name: terrain_sensor_app
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=1883
    depends_on:
      - mqtt-broker
