SEEDS_DATA = [
    {
        "key": "tomato",
        "name_it": "Pomodoro",
        "min_soilmoisture": 0.250,
        "max_soilmoisture": 0.300,
        "min_temperature": 18,
        "max_temperature": 27,
        "ideal_soil": "Franco",
        "days": 60,
        "seasons": ["Primavera", "Estate"],
    },
    {
        "key": "zucchini",
        "name_it": "Zucchine",
        "min_soilmoisture": 0.260,
        "max_soilmoisture": 0.310,
        "min_temperature": 18,
        "max_temperature": 28,
        "ideal_soil": "Franco",
        "days": 50,
        "seasons": ["Primavera", "Estate"],
    },
    {
        "key": "lettuce",
        "name_it": "Insalata",
        "min_soilmoisture": 0.280,
        "max_soilmoisture": 0.330,
        "min_temperature": 10,
        "max_temperature": 20,
        "ideal_soil": "Sabbioso",
        "days": 30,
        "seasons": ["Primavera", "Autunno"],
    },
    {
        "key": "carrot",
        "name_it": "Carote",
        "min_soilmoisture": 0.240,
        "max_soilmoisture": 0.290,
        "min_temperature": 15,
        "max_temperature": 22,
        "ideal_soil": "Franco-Sabbioso",
        "days": 70,
        "seasons": ["Primavera", "Autunno"],
    },
    {
        "key": "bean",
        "name_it": "Fagioli",
        "min_soilmoisture": 0.250,
        "max_soilmoisture": 0.300,
        "min_temperature": 18,
        "max_temperature": 26,
        "ideal_soil": "Franco",
        "days": 60,
        "seasons": ["Primavera", "Estate"],
    },
    {
        "key": "pea",
        "name_it": "Piselli",
        "min_soilmoisture": 0.240,
        "max_soilmoisture": 0.290,
        "min_temperature": 10,
        "max_temperature": 18,
        "ideal_soil": "Franco-Sabbioso",
        "days": 65,
        "seasons": ["Primavera", "Autunno", "Inverno"],
    },
    {
        "key": "spinach",
        "name_it": "Spinaci",
        "min_soilmoisture": 0.300,
        "max_soilmoisture": 0.350,
        "min_temperature": 8,
        "max_temperature": 18,
        "ideal_soil": "Franco",
        "days": 40,
        "seasons": ["Autunno", "Inverno", "Primavera"],
    },
    {
        "key": "eggplant",
        "name_it": "Melanzane",
        "min_soilmoisture": 0.260,
        "max_soilmoisture": 0.310,
        "min_temperature": 20,
        "max_temperature": 30,
        "ideal_soil": "Franco-Argilloso",
        "days": 80,
        "seasons": ["Primavera", "Estate"],
    },
    {
        "key": "bell_pepper",
        "name_it": "Peperoni",
        "min_soilmoisture": 0.250,
        "max_soilmoisture": 0.300,
        "min_temperature": 20,
        "max_temperature": 30,
        "ideal_soil": "Franco-Argilloso",
        "days": 75,
        "seasons": ["Primavera", "Estate"],
    },
    {
        "key": "cucumber",
        "name_it": "Cetrioli",
        "min_soilmoisture": 0.280,
        "max_soilmoisture": 0.330,
        "min_temperature": 18,
        "max_temperature": 28,
        "ideal_soil": "Franco",
        "days": 55,
        "seasons": ["Primavera", "Estate"],
    },
    {
        "key": "corn",
        "name_it": "Mais",
        "min_soilmoisture": 0.220,
        "max_soilmoisture": 0.270,
        "min_temperature": 18,
        "max_temperature": 30,
        "ideal_soil": "Franco",
        "days": 75,
        "seasons": ["Primavera", "Estate"],
    },
    {
        "key": "wheat",
        "name_it": "Grano",
        "min_soilmoisture": 0.180,
        "max_soilmoisture": 0.230,
        "min_temperature": 10,
        "max_temperature": 24,
        "ideal_soil": "Argilloso",
        "days": 90,
        "seasons": ["Autunno", "Inverno"],
    },
    {
        "key": "basil",
        "name_it": "Basilico",
        "min_soilmoisture": 0.250,
        "max_soilmoisture": 0.300,
        "min_temperature": 18,
        "max_temperature": 28,
        "ideal_soil": "Franco-Sabbioso",
        "days": 40,
        "seasons": ["Primavera", "Estate"],
    },
    {
        "key": "pumpkin",
        "name_it": "Zucca",
        "min_soilmoisture": 0.250,
        "max_soilmoisture": 0.300,
        "min_temperature": 18,
        "max_temperature": 27,
        "ideal_soil": "Franco",
        "days": 100,
        "seasons": ["Primavera", "Estate"],
    },
    {
        "key": "cabbage",
        "name_it": "Cavolo",
        "min_soilmoisture": 0.270,
        "max_soilmoisture": 0.320,
        "min_temperature": 10,
        "max_temperature": 20,
        "ideal_soil": "Franco-Argilloso",
        "days": 85,
        "seasons": ["Autunno", "Inverno"],
    },
    {
        "key": "garlic",
        "name_it": "Aglio",
        "min_soilmoisture": 0.180,
        "max_soilmoisture": 0.230,
        "min_temperature": 5,
        "max_temperature": 18,
        "ideal_soil": "Sabbioso",
        "days": 180,
        "seasons": ["Autunno", "Inverno"],
    },
    {
        "key": "onion",
        "name_it": "Cipolla",
        "min_soilmoisture": 0.200,
        "max_soilmoisture": 0.250,
        "min_temperature": 13,
        "max_temperature": 24,
        "ideal_soil": "Franco-Sabbioso",
        "days": 120,
        "seasons": ["Primavera", "Autunno"],
    },
    {
        "key": "strawberry",
        "name_it": "Fragole",
        "min_soilmoisture": 0.280,
        "max_soilmoisture": 0.330,
        "min_temperature": 15,
        "max_temperature": 25,
        "ideal_soil": "Sabbioso",
        "days": 90,
        "seasons": ["Primavera", "Autunno"],
    },
    {
        "key": "sunflower",
        "name_it": "Girasole",
        "min_soilmoisture": 0.180,
        "max_soilmoisture": 0.230,
        "min_temperature": 18,
        "max_temperature": 28,
        "ideal_soil": "Argilloso",
        "days": 90,
        "seasons": ["Primavera", "Estate"],
    },
    {
        "key": "arugula",
        "name_it": "Rucola",
        "min_soilmoisture": 0.250,
        "max_soilmoisture": 0.300,
        "min_temperature": 10,
        "max_temperature": 22,
        "ideal_soil": "Franco-Sabbioso",
        "days": 30,
        "seasons": ["Primavera", "Autunno"],
    },
]

# Alias per retrocompatibilità con core/seed_matcher.py
list_seeds = [
    {
        "name": seed["key"],
        "name_it": seed["name_it"],
        "min_soilmoisture": int(seed["min_soilmoisture"] * 100),
        "max_soilmoisture": int(seed["max_soilmoisture"] * 100),
        "min_temperature": seed["min_temperature"],
        "max_temperature": seed["max_temperature"],
        "ideal_soil": seed["ideal_soil"],
        "time_harvest": (seed["days"], seed["days"] + 20),
        "seasons": seed["seasons"],
    }
    for seed in SEEDS_DATA
]

CROPS_INFO = {
    seed["name_it"]: {
        "key": seed["key"],
        "threshold": seed["min_soilmoisture"],
        "max_threshold": seed["max_soilmoisture"],
        "ideal_soil": seed["ideal_soil"],
        "days": seed["days"],
        "min_temp": seed["min_temperature"],
        "max_temp": seed["max_temperature"],
        "seasons": seed["seasons"],
    }
    for seed in SEEDS_DATA
}

CROP_KEY_TO_NAME = {}
for seed in SEEDS_DATA:
    key_eng = seed["key"].lower()
    name_it = seed["name_it"]
    CROP_KEY_TO_NAME[key_eng] = name_it
    CROP_KEY_TO_NAME[name_it.lower()] = name_it
    if key_eng == "bell_pepper":
        CROP_KEY_TO_NAME["bell pepper"] = name_it
        CROP_KEY_TO_NAME["peperoni"] = name_it