per_listener_settings true

listener 8883
allow_anonymous false
password_file /mosquitto/config/passwd

cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key