# Base list of raw crop specifications
SEEDS_DATA = [
    {
        "key": "tomato",
        "name_it": "Pomodoro",
        "min_soilmoisture": 0.250,
        "max_soilmoisture": 0.300,
        "min_temperature": 18,
        "max_temperature": 27,
        "ideal_soil": "Franco",
        "days": 60,
        "seasons": ["spring", "summer", "primavera", "estate"],
    },
    {
        "key": "zucchini",
        "name_it": "Zucchine",
        "min_soilmoisture": 0.260,
        "max_soilmoisture": 0.310,
        "min_temperature": 18,
        "max_temperature": 28,
        "ideal_soil": "Franco",
        "days": 50,
        "seasons": ["spring", "summer", "primavera", "estate"],
    },
    {
        "key": "lettuce",
        "name_it": "Insalata",
        "min_soilmoisture": 0.280,
        "max_soilmoisture": 0.330,
        "min_temperature": 10,
        "max_temperature": 20,
        "ideal_soil": "Sabbioso",
        "days": 30,
        "seasons": ["spring", "autumn", "fall", "primavera", "autunno"],
    },
    {
        "key": "carrot",
        "name_it": "Carote",
        "min_soilmoisture": 0.240,
        "max_soilmoisture": 0.290,
        "min_temperature": 15,
        "max_temperature": 22,
        "ideal_soil": "Franco-Sabbioso",
        "days": 70,
        "seasons": ["spring", "autumn", "fall", "primavera", "autunno"],
    },
    {
        "key": "bean",
        "name_it": "Fagioli",
        "min_soilmoisture": 0.250,
        "max_soilmoisture": 0.300,
        "min_temperature": 18,
        "max_temperature": 26,
        "ideal_soil": "Franco",
        "days": 60,
        "seasons": ["spring", "summer", "primavera", "estate"],
    },
    {
        "key": "pea",
        "name_it": "Piselli",
        "min_soilmoisture": 0.240,
        "max_soilmoisture": 0.290,
        "min_temperature": 10,
        "max_temperature": 18,
        "ideal_soil": "Franco-Sabbioso",
        "days": 65,
        "seasons": [
            "spring",
            "autumn",
            "fall",
            "winter",
            "primavera",
            "autunno",
            "inverno",
        ],
    },
    {
        "key": "spinach",
        "name_it": "Spinaci",
        "min_soilmoisture": 0.300,
        "max_soilmoisture": 0.350,
        "min_temperature": 8,
        "max_temperature": 18,
        "ideal_soil": "Franco",
        "days": 40,
        "seasons": [
            "autumn",
            "fall",
            "winter",
            "spring",
            "autunno",
            "inverno",
            "primavera",
        ],
    },
    {
        "key": "eggplant",
        "name_it": "Melanzane",
        "min_soilmoisture": 0.260,
        "max_soilmoisture": 0.310,
        "min_temperature": 20,
        "max_temperature": 30,
        "ideal_soil": "Franco-Argilloso",
        "days": 80,
        "seasons": ["spring", "summer", "primavera", "estate"],
    },
    {
        "key": "bell_pepper",
        "name_it": "Peperoni",
        "min_soilmoisture": 0.250,
        "max_soilmoisture": 0.300,
        "min_temperature": 20,
        "max_temperature": 30,
        "ideal_soil": "Franco-Argilloso",
        "days": 75,
        "seasons": ["spring", "summer", "primavera", "estate"],
    },
    {
        "key": "cucumber",
        "name_it": "Cetrioli",
        "min_soilmoisture": 0.280,
        "max_soilmoisture": 0.330,
        "min_temperature": 18,
        "max_temperature": 28,
        "ideal_soil": "Franco",
        "days": 55,
        "seasons": ["spring", "summer", "primavera", "estate"],
    },
    {
        "key": "corn",
        "name_it": "Mais",
        "min_soilmoisture": 0.220,
        "max_soilmoisture": 0.270,
        "min_temperature": 18,
        "max_temperature": 30,
        "ideal_soil": "Franco",
        "days": 75,
        "seasons": ["spring", "summer", "primavera", "estate"],
    },
    {
        "key": "wheat",
        "name_it": "Grano",
        "min_soilmoisture": 0.180,
        "max_soilmoisture": 0.230,
        "min_temperature": 10,
        "max_temperature": 24,
        "ideal_soil": "Argilloso",
        "days": 90,
        "seasons": ["autumn", "fall", "winter", "autunno", "inverno"],
    },
    {
        "key": "basil",
        "name_it": "Basilico",
        "min_soilmoisture": 0.250,
        "max_soilmoisture": 0.300,
        "min_temperature": 18,
        "max_temperature": 28,
        "ideal_soil": "Franco-Sabbioso",
        "days": 40,
        "seasons": ["spring", "summer", "primavera", "estate"],
    },
    {
        "key": "pumpkin",
        "name_it": "Zucca",
        "min_soilmoisture": 0.250,
        "max_soilmoisture": 0.300,
        "min_temperature": 18,
        "max_temperature": 27,
        "ideal_soil": "Franco",
        "days": 100,
        "seasons": ["spring", "summer", "primavera", "estate"],
    },
    {
        "key": "cabbage",
        "name_it": "Cavolo",
        "min_soilmoisture": 0.270,
        "max_soilmoisture": 0.320,
        "min_temperature": 10,
        "max_temperature": 20,
        "ideal_soil": "Franco-Argilloso",
        "days": 85,
        "seasons": ["autumn", "fall", "winter", "autunno", "inverno"],
    },
    {
        "key": "garlic",
        "name_it": "Aglio",
        "min_soilmoisture": 0.180,
        "max_soilmoisture": 0.230,
        "min_temperature": 5,
        "max_temperature": 18,
        "ideal_soil": "Sabbioso",
        "days": 180,
        "seasons": ["autumn", "fall", "winter", "autunno", "inverno"],
    },
    {
        "key": "onion",
        "name_it": "Cipolla",
        "min_soilmoisture": 0.200,
        "max_soilmoisture": 0.250,
        "min_temperature": 13,
        "max_temperature": 24,
        "ideal_soil": "Franco-Sabbioso",
        "days": 120,
        "seasons": ["spring", "autumn", "fall", "primavera", "autunno"],
    },
    {
        "key": "strawberry",
        "name_it": "Fragole",
        "min_soilmoisture": 0.280,
        "max_soilmoisture": 0.330,
        "min_temperature": 15,
        "max_temperature": 25,
        "ideal_soil": "Sabbioso",
        "days": 90,
        "seasons": ["spring", "autumn", "fall", "primavera", "autunno"],
    },
    {
        "key": "sunflower",
        "name_it": "Girasole",
        "min_soilmoisture": 0.180,
        "max_soilmoisture": 0.230,
        "min_temperature": 18,
        "max_temperature": 28,
        "ideal_soil": "Argilloso",
        "days": 90,
        "seasons": ["spring", "summer", "primavera", "estate"],
    },
    {
        "key": "arugula",
        "name_it": "Rucola",
        "min_soilmoisture": 0.250,
        "max_soilmoisture": 0.300,
        "min_temperature": 10,
        "max_temperature": 22,
        "ideal_soil": "Franco-Sabbioso",
        "days": 30,
        "seasons": ["spring", "autumn", "fall", "primavera", "autunno"],
    },
    {
        "key": "olive",
        "name_it": "Oliva",
        "min_soilmoisture": 0.350,
        "max_soilmoisture": 0.400,
        "min_temperature": 12,
        "max_temperature": 32,
        "ideal_soil": "Franco-sabbioso",
        "days": 60,
        "seasons": ["spring", "autumn", "fall", "primavera", "autunno"],
    },
]

# Processed seed dictionaries converted into percentage values for runtime lookup
SEEDS_LST = [
    {
        "name": seed["key"],
        "name_it": seed["name_it"],
        "min_soilmoisture": int(seed["min_soilmoisture"] * 100),
        "max_soilmoisture": int(seed["max_soilmoisture"] * 100),
        "min_temperature": seed["min_temperature"],
        "max_temperature": seed["max_temperature"],
        "ideal_soil": seed["ideal_soil"],
        "time_harvest": (seed["days"], seed["days"] + 20),
        "seasons": seed["seasons"],
    }
    for seed in SEEDS_DATA
]
