list_seeds = [
    {
        "name": "tomato",
        "min_soilmoisture": 60, "max_soilmoisture": 80,
        "min_temperature": 18, "max_temperature": 27,
        "seasons": ["spring", "summer"],
        "time_harvest": (60, 90),
    },
    {
        "name": "zucchini",
        "min_soilmoisture": 55, "max_soilmoisture": 75,
        "min_temperature": 18, "max_temperature": 28,
        "seasons": ["spring", "summer"],
        "time_harvest": (45, 60),
    },
    {
        "name": "lettuce",
        "min_soilmoisture": 60, "max_soilmoisture": 80,
        "min_temperature": 10, "max_temperature": 20,
        "seasons": ["spring", "autumn"],
        "time_harvest": (40, 60),
    },
    {
        "name": "carrot",
        "min_soilmoisture": 50, "max_soilmoisture": 70,
        "min_temperature": 15, "max_temperature": 22,
        "seasons": ["spring", "autumn"],
        "time_harvest": (70, 100),
    },
    {
        "name": "bean",
        "min_soilmoisture": 55, "max_soilmoisture": 75,
        "min_temperature": 18, "max_temperature": 26,
        "seasons": ["spring", "summer"],
        "time_harvest": (50, 70),
    },
    {
        "name": "pea",
        "min_soilmoisture": 55, "max_soilmoisture": 75,
        "min_temperature": 10, "max_temperature": 18,
        "seasons": ["spring", "autumn", "winter"],
        "time_harvest": (60, 70),
    },
    {
        "name": "spinach",
        "min_soilmoisture": 60, "max_soilmoisture": 80,
        "min_temperature": 8, "max_temperature": 18,
        "seasons": ["autumn", "winter", "spring"],
        "time_harvest": (35, 50),
    },
    {
        "name": "eggplant",
        "min_soilmoisture": 60, "max_soilmoisture": 80,
        "min_temperature": 20, "max_temperature": 30,
        "seasons": ["spring", "summer"],
        "time_harvest": (70, 90),
    },
    {
        "name": "bell pepper",
        "min_soilmoisture": 55, "max_soilmoisture": 75,
        "min_temperature": 20, "max_temperature": 30,
        "seasons": ["spring", "summer"],
        "time_harvest": (60, 90),
    },
    {
        "name": "cucumber",
        "min_soilmoisture": 65, "max_soilmoisture": 85,
        "min_temperature": 18, "max_temperature": 28,
        "seasons": ["spring", "summer"],
        "time_harvest": (45, 60),
    },
    {
        "name": "corn",
        "min_soilmoisture": 55, "max_soilmoisture": 75,
        "min_temperature": 18, "max_temperature": 30,
        "seasons": ["spring", "summer"],
        "time_harvest": (80, 100),
    },
    {
        "name": "wheat",
        "min_soilmoisture": 40, "max_soilmoisture": 60,
        "min_temperature": 10, "max_temperature": 24,
        "seasons": ["autumn", "winter"],
        "time_harvest": (180, 240),
    },
    {
        "name": "basil",
        "min_soilmoisture": 55, "max_soilmoisture": 75,
        "min_temperature": 18, "max_temperature": 28,
        "seasons": ["spring", "summer"],
        "time_harvest": (30, 60),
    },
    {
        "name": "pumpkin",
        "min_soilmoisture": 55, "max_soilmoisture": 75,
        "min_temperature": 18, "max_temperature": 27,
        "seasons": ["spring", "summer"],
        "time_harvest": (90, 120),
    },
    {
        "name": "cabbage",
        "min_soilmoisture": 60, "max_soilmoisture": 80,
        "min_temperature": 10, "max_temperature": 20,
        "seasons": ["autumn", "winter"],
        "time_harvest": (70, 100),
    },
    {
        "name": "garlic",
        "min_soilmoisture": 40, "max_soilmoisture": 60,
        "min_temperature": 5, "max_temperature": 18,
        "seasons": ["autumn", "winter"],
        "time_harvest": (180, 240),
    },
    {
        "name": "onion",
        "min_soilmoisture": 45, "max_soilmoisture": 65,
        "min_temperature": 13, "max_temperature": 24,
        "seasons": ["spring", "autumn"],
        "time_harvest": (100, 150),
    },
    {
        "name": "strawberry",
        "min_soilmoisture": 60, "max_soilmoisture": 80,
        "min_temperature": 15, "max_temperature": 25,
        "seasons": ["spring", "autumn"],
        "time_harvest": (90, 120),
    },
    {
        "name": "sunflower",
        "min_soilmoisture": 40, "max_soilmoisture": 60,
        "min_temperature": 18, "max_temperature": 28,
        "seasons": ["spring", "summer"],
        "time_harvest": (80, 100),
    },
    {
        "name": "arugula",
        "min_soilmoisture": 55, "max_soilmoisture": 75,
        "min_temperature": 10, "max_temperature": 22,
        "seasons": ["spring", "autumn"],
        "time_harvest": (25, 40),
    },
]