KNOWN_CAMPS = ["campo_1", "campo_2", "campo_3"]

SEEDS_LST = [
    {
        "name": "tomato",
        "min_soilmoisture": 60,
        "max_soilmoisture": 80,
        "min_temperature": 18,
        "max_temperature": 27,
        "seasons": ["spring", "summer"],
        "time_harvest": (60, 90),
    },
    {
        "name": "zucchini",
        "min_soilmoisture": 55,
        "max_soilmoisture": 75,
        "min_temperature": 18,
        "max_temperature": 28,
        "seasons": ["spring", "summer"],
        "time_harvest": (45, 60),
    },
    {
        "name": "lettuce",
        "min_soilmoisture": 60,
        "max_soilmoisture": 80,
        "min_temperature": 10,
        "max_temperature": 20,
        "seasons": ["spring", "autumn"],
        "time_harvest": (40, 60),
    },
    {
        "name": "carrot",
        "min_soilmoisture": 50,
        "max_soilmoisture": 70,
        "min_temperature": 15,
        "max_temperature": 22,
        "seasons": ["spring", "autumn"],
        "time_harvest": (70, 100),
    },
    {
        "name": "bean",
        "min_soilmoisture": 55,
        "max_soilmoisture": 75,
        "min_temperature": 18,
        "max_temperature": 26,
        "seasons": ["spring", "summer"],
        "time_harvest": (50, 70),
    },
    {
        "name": "pea",
        "min_soilmoisture": 55,
        "max_soilmoisture": 75,
        "min_temperature": 10,
        "max_temperature": 18,
        "seasons": ["spring", "autumn", "winter"],
        "time_harvest": (60, 70),
    },
    {
        "name": "spinach",
        "min_soilmoisture": 60,
        "max_soilmoisture": 80,
        "min_temperature": 8,
        "max_temperature": 18,
        "seasons": ["autumn", "winter", "spring"],
        "time_harvest": (35, 50),
    },
    {
        "name": "eggplant",
        "min_soilmoisture": 60,
        "max_soilmoisture": 80,
        "min_temperature": 20,
        "max_temperature": 30,
        "seasons": ["spring", "summer"],
        "time_harvest": (70, 90),
    },
    {
        "name": "bell pepper",
        "min_soilmoisture": 55,
        "max_soilmoisture": 75,
        "min_temperature": 20,
        "max_temperature": 30,
        "seasons": ["spring", "summer"],
        "time_harvest": (60, 90),
    },
    {
        "name": "cucumber",
        "min_soilmoisture": 65,
        "max_soilmoisture": 85,
        "min_temperature": 18,
        "max_temperature": 28,
        "seasons": ["spring", "summer"],
        "time_harvest": (45, 60),
    },
    {
        "name": "corn",
        "min_soilmoisture": 55,
        "max_soilmoisture": 75,
        "min_temperature": 18,
        "max_temperature": 30,
        "seasons": ["spring", "summer"],
        "time_harvest": (80, 100),
    },
    {
        "name": "wheat",
        "min_soilmoisture": 40,
        "max_soilmoisture": 60,
        "min_temperature": 10,
        "max_temperature": 24,
        "seasons": ["autumn", "winter"],
        "time_harvest": (180, 240),
    },
    {
        "name": "basil",
        "min_soilmoisture": 55,
        "max_soilmoisture": 75,
        "min_temperature": 18,
        "max_temperature": 28,
        "seasons": ["spring", "summer"],
        "time_harvest": (30, 60),
    },
    {
        "name": "pumpkin",
        "min_soilmoisture": 55,
        "max_soilmoisture": 75,
        "min_temperature": 18,
        "max_temperature": 27,
        "seasons": ["spring", "summer"],
        "time_harvest": (90, 120),
    },
    {
        "name": "cabbage",
        "min_soilmoisture": 60,
        "max_soilmoisture": 80,
        "min_temperature": 10,
        "max_temperature": 20,
        "seasons": ["autumn", "winter"],
        "time_harvest": (70, 100),
    },
    {
        "name": "garlic",
        "min_soilmoisture": 40,
        "max_soilmoisture": 60,
        "min_temperature": 5,
        "max_temperature": 18,
        "seasons": ["autumn", "winter"],
        "time_harvest": (180, 240),
    },
    {
        "name": "onion",
        "min_soilmoisture": 45,
        "max_soilmoisture": 65,
        "min_temperature": 13,
        "max_temperature": 24,
        "seasons": ["spring", "autumn"],
        "time_harvest": (100, 150),
    },
    {
        "name": "strawberry",
        "min_soilmoisture": 60,
        "max_soilmoisture": 80,
        "min_temperature": 15,
        "max_temperature": 25,
        "seasons": ["spring", "autumn"],
        "time_harvest": (90, 120),
    },
    {
        "name": "sunflower",
        "min_soilmoisture": 40,
        "max_soilmoisture": 60,
        "min_temperature": 18,
        "max_temperature": 28,
        "seasons": ["spring", "summer"],
        "time_harvest": (80, 100),
    },
    {
        "name": "arugula",
        "min_soilmoisture": 55,
        "max_soilmoisture": 75,
        "min_temperature": 10,
        "max_temperature": 22,
        "seasons": ["spring", "autumn"],
        "time_harvest": (25, 40),
    },
    {
        "name": "olive",
        "min_soilmoisture": 35,
        "max_soilmoisture": 55,
        "min_temperature": 12,
        "max_temperature": 32,
        "seasons": ["spring", "autumn"],
        "time_harvest": (180, 210),
    },
    {
        "name": "grape",
        "min_soilmoisture": 35,
        "max_soilmoisture": 55,
        "min_temperature": 15,
        "max_temperature": 30,
        "seasons": ["spring", "summer"],
        "time_harvest": (120, 150),
    },
    {
        "name": "potato",
        "min_soilmoisture": 55,
        "max_soilmoisture": 75,
        "min_temperature": 12,
        "max_temperature": 22,
        "seasons": ["spring", "summer"],
        "time_harvest": (90, 110),
    },
    {
        "name": "apple",
        "min_soilmoisture": 45,
        "max_soilmoisture": 65,
        "min_temperature": 10,
        "max_temperature": 25,
        "seasons": ["spring", "autumn"],
        "time_harvest": (150, 180),
    },
    {
        "name": "peach",
        "min_soilmoisture": 45,
        "max_soilmoisture": 65,
        "min_temperature": 15,
        "max_temperature": 28,
        "seasons": ["spring", "summer"],
        "time_harvest": (120, 150),
    },
    {
        "name": "citrus",
        "min_soilmoisture": 40,
        "max_soilmoisture": 60,
        "min_temperature": 13,
        "max_temperature": 30,
        "seasons": ["spring", "autumn"],
        "time_harvest": (180, 210),
    },
    {
        "name": "soy",
        "min_soilmoisture": 50,
        "max_soilmoisture": 70,
        "min_temperature": 18,
        "max_temperature": 28,
        "seasons": ["spring", "summer"],
        "time_harvest": (100, 130),
    },
    {
        "name": "melon",
        "min_soilmoisture": 60,
        "max_soilmoisture": 80,
        "min_temperature": 20,
        "max_temperature": 32,
        "seasons": ["spring", "summer"],
        "time_harvest": (70, 85),
    },
    {
        "name": "watermelon",
        "min_soilmoisture": 60,
        "max_soilmoisture": 80,
        "min_temperature": 22,
        "max_temperature": 34,
        "seasons": ["spring", "summer"],
        "time_harvest": (75, 90),
    },
    {
        "name": "broccoli",
        "min_soilmoisture": 55,
        "max_soilmoisture": 75,
        "min_temperature": 10,
        "max_temperature": 20,
        "seasons": ["autumn", "winter"],
        "time_harvest": (60, 75),
    },
    {
        "name": "cauliflower",
        "min_soilmoisture": 55,
        "max_soilmoisture": 75,
        "min_temperature": 10,
        "max_temperature": 20,
        "seasons": ["autumn", "winter"],
        "time_harvest": (70, 90),
    },
    {
        "name": "rice",
        "min_soilmoisture": 70,
        "max_soilmoisture": 90,
        "min_temperature": 20,
        "max_temperature": 32,
        "seasons": ["spring", "summer"],
        "time_harvest": (130, 160),
    },
    {
        "name": "barley",
        "min_soilmoisture": 40,
        "max_soilmoisture": 60,
        "min_temperature": 10,
        "max_temperature": 22,
        "seasons": ["autumn", "winter"],
        "time_harvest": (120, 150),
    },
    {
        "name": "oats",
        "min_soilmoisture": 40,
        "max_soilmoisture": 60,
        "min_temperature": 10,
        "max_temperature": 22,
        "seasons": ["autumn", "winter"],
        "time_harvest": (120, 150),
    },
    {
        "name": "almond",
        "min_soilmoisture": 35,
        "max_soilmoisture": 55,
        "min_temperature": 15,
        "max_temperature": 32,
        "seasons": ["spring", "summer"],
        "time_harvest": (180, 210),
    },
    {
        "name": "walnut",
        "min_soilmoisture": 40,
        "max_soilmoisture": 60,
        "min_temperature": 12,
        "max_temperature": 28,
        "seasons": ["spring", "autumn"],
        "time_harvest": (180, 210),
    },
    {
        "name": "alfalfa",
        "min_soilmoisture": 45,
        "max_soilmoisture": 65,
        "min_temperature": 12,
        "max_temperature": 26,
        "seasons": ["spring", "summer"],
        "time_harvest": (45, 60),
    },
]

DEFAULT_FORMAT = f" %(asctime)s | " "%(levelname)s | " "%(message)s"
DEFAULT_DATE_FORMAT = "%Y-%m-%d %H:%M:%S"